import { createStubProvider } from "@/sources/types";
import type { EventCard } from "@/types";

// Demo dataset — ~100 fake upcoming events distributed across Luma, Meetup,
// Ticketmaster, and Eventbrite for demo and testing purposes.

const DEMO_EVENTS: Partial<EventCard>[] = [

  // ─── Luma (25) ───────────────────────────────────────────────────────────────

  {
    id: "luma-d001", source: "luma", format: "conference", price: "paid", priceAmount: 149, currency: "EUR",
    title: "AI Founders Summit 2026", date: "Apr 3, 2026", location: "Milan, Italy",
    topics: ["AI", "Startups", "Entrepreneurship"], attendeeProfile: "AI startup founders and investors",
    url: "https://lu.ma/ai-founders-summit-2026",
  },
  {
    id: "luma-d002", source: "luma", format: "workshop", price: "paid", priceAmount: 79, currency: "EUR",
    title: "LLM Engineering Workshop", date: "Apr 7, 2026", location: "Berlin, Germany",
    topics: ["AI", "LLM", "Python"], attendeeProfile: "ML engineers and developers",
    url: "https://lu.ma/llm-engineering-workshop",
  },
  {
    id: "luma-d003", source: "luma", format: "meetup", price: "free",
    title: "Startup Pitch Night Milan", date: "Apr 10, 2026", location: "Milan, Italy",
    topics: ["Startups", "Fundraising", "Networking"], attendeeProfile: "Founders and early-stage investors",
    url: "https://lu.ma/startup-pitch-milan",
  },
  {
    id: "luma-d004", source: "luma", format: "conference", price: "paid", priceAmount: 199, currency: "EUR",
    title: "React Advanced Europe 2026", date: "Apr 14, 2026", location: "Amsterdam, Netherlands",
    topics: ["React", "TypeScript", "Frontend"], attendeeProfile: "Frontend engineers",
    url: "https://lu.ma/react-advanced-europe",
  },
  {
    id: "luma-d005", source: "luma", format: "meetup", price: "free",
    title: "Product Hunt Demo Day Berlin", date: "Apr 17, 2026", location: "Berlin, Germany",
    topics: ["Product", "Startups", "Networking"], attendeeProfile: "Product makers and indie hackers",
    url: "https://lu.ma/ph-demo-day-berlin",
  },
  {
    id: "luma-d006", source: "luma", format: "hackathon", price: "free",
    title: "AI for Healthcare Hackathon", date: "Apr 19, 2026", location: "Rome, Italy",
    topics: ["AI", "Healthcare", "Machine Learning"], attendeeProfile: "Developers and healthcare professionals",
    url: "https://lu.ma/ai-healthcare-hack",
  },
  {
    id: "luma-d007", source: "luma", format: "workshop", price: "paid", priceAmount: 59, currency: "EUR",
    title: "TypeScript Deep Dive Workshop", date: "Apr 22, 2026", location: "Barcelona, Spain",
    topics: ["TypeScript", "JavaScript", "Frontend"], attendeeProfile: "JavaScript developers",
    url: "https://lu.ma/typescript-deep-dive",
  },
  {
    id: "luma-d008", source: "luma", format: "conference", price: "paid", priceAmount: 249, currency: "EUR",
    title: "Web3 Developer Summit", date: "Apr 25, 2026", location: "Lisbon, Portugal",
    topics: ["Web3", "Blockchain", "Crypto"], attendeeProfile: "Web3 developers and DeFi builders",
    url: "https://lu.ma/web3-dev-summit",
  },
  {
    id: "luma-d009", source: "luma", format: "conference", price: "paid", priceAmount: 129, currency: "EUR",
    title: "Design Systems Conference 2026", date: "Apr 28, 2026", location: "Berlin, Germany",
    topics: ["Design", "UI", "Product"], attendeeProfile: "Designers and frontend engineers",
    url: "https://lu.ma/design-systems-conf",
  },
  {
    id: "luma-d010", source: "luma", format: "hackathon", price: "free",
    title: "Vibe Coding Hackathon Milan", date: "May 2, 2026", location: "Milan, Italy",
    topics: ["AI", "Agents", "LLM"], attendeeProfile: "Developers and AI enthusiasts",
    url: "https://lu.ma/vibe-coding-milan",
  },
  {
    id: "luma-d011", source: "luma", format: "conference", price: "free",
    title: "Open AI Day London", date: "May 6, 2026", location: "London, UK",
    topics: ["AI", "Machine Learning", "Open Source"], attendeeProfile: "AI researchers and practitioners",
    url: "https://lu.ma/open-ai-day-london",
  },
  {
    id: "luma-d012", source: "luma", format: "workshop", price: "paid", priceAmount: 89, currency: "EUR",
    title: "SaaS Growth Playbook", date: "May 9, 2026", location: "Amsterdam, Netherlands",
    topics: ["SaaS", "Growth", "B2B"], attendeeProfile: "SaaS founders and growth marketers",
    url: "https://lu.ma/saas-growth-playbook",
  },
  {
    id: "luma-d013", source: "luma", format: "meetup", price: "free",
    title: "Figma Community Meetup Paris", date: "May 13, 2026", location: "Paris, France",
    topics: ["Design", "Figma", "UI"], attendeeProfile: "Product designers and UX practitioners",
    url: "https://lu.ma/figma-community-paris",
  },
  {
    id: "luma-d014", source: "luma", format: "conference", price: "paid", priceAmount: 179, currency: "EUR",
    title: "Cloud Native Day Madrid", date: "May 16, 2026", location: "Madrid, Spain",
    topics: ["Cloud", "Kubernetes", "DevOps"], attendeeProfile: "DevOps engineers and SREs",
    url: "https://lu.ma/cloud-native-madrid",
  },
  {
    id: "luma-d015", source: "luma", format: "conference", price: "paid", priceAmount: 99, currency: "EUR",
    title: "Python Data Summit Turin", date: "May 20, 2026", location: "Turin, Italy",
    topics: ["Python", "Data Science", "Analytics"], attendeeProfile: "Data scientists and analysts",
    url: "https://lu.ma/python-data-summit",
  },
  {
    id: "luma-d016", source: "luma", format: "workshop", price: "paid", priceAmount: 199, currency: "EUR",
    title: "Generative AI Bootcamp", date: "May 23, 2026", location: "Milan, Italy",
    topics: ["AI", "LLM", "Agents"], attendeeProfile: "Developers building AI products",
    url: "https://lu.ma/gen-ai-bootcamp-milan",
  },
  {
    id: "luma-d017", source: "luma", format: "conference", price: "paid", priceAmount: 299, currency: "EUR",
    title: "Startup Ecosystem Week Berlin", date: "May 26, 2026", location: "Berlin, Germany",
    topics: ["Startups", "VC", "Entrepreneurship"], attendeeProfile: "Startup founders and VCs",
    url: "https://lu.ma/startup-ecosystem-berlin",
  },
  {
    id: "luma-d018", source: "luma", format: "conference", price: "paid", priceAmount: 349, currency: "EUR",
    title: "FinTech Innovation Forum", date: "May 29, 2026", location: "London, UK",
    topics: ["Fintech", "Payments", "AI"], attendeeProfile: "Fintech professionals and investors",
    url: "https://lu.ma/fintech-innovation-forum",
  },
  {
    id: "luma-d019", source: "luma", format: "conference", price: "paid", priceAmount: 129, currency: "EUR",
    title: "ML Engineers Summit Amsterdam", date: "Jun 3, 2026", location: "Amsterdam, Netherlands",
    topics: ["Machine Learning", "AI", "Python"], attendeeProfile: "ML engineers and data scientists",
    url: "https://lu.ma/ml-engineers-summit",
  },
  {
    id: "luma-d020", source: "luma", format: "workshop", price: "paid", priceAmount: 69, currency: "EUR",
    title: "Product Design Sprint Rome", date: "Jun 6, 2026", location: "Rome, Italy",
    topics: ["Design", "Product", "UX"], attendeeProfile: "Product managers and designers",
    url: "https://lu.ma/product-design-sprint-rome",
  },
  {
    id: "luma-d021", source: "luma", format: "meetup", price: "free",
    title: "AI Safety Workshop Paris", date: "Jun 10, 2026", location: "Paris, France",
    topics: ["AI", "Machine Learning"], attendeeProfile: "AI researchers and ethicists",
    url: "https://lu.ma/ai-safety-workshop-paris",
  },
  {
    id: "luma-d022", source: "luma", format: "workshop", price: "paid", priceAmount: 49, currency: "EUR",
    title: "B2B Sales Masterclass Milan", date: "Jun 13, 2026", location: "Milan, Italy",
    topics: ["B2B", "Sales", "SaaS"], attendeeProfile: "Sales professionals and founders",
    url: "https://lu.ma/b2b-sales-masterclass",
  },
  {
    id: "luma-d023", source: "luma", format: "conference", price: "paid", priceAmount: 159, currency: "EUR",
    title: "Rust Systems Programming Day", date: "Jun 17, 2026", location: "Berlin, Germany",
    topics: ["Rust", "Backend", "Cloud"], attendeeProfile: "Systems engineers and Rust developers",
    url: "https://lu.ma/rust-systems-day",
  },
  {
    id: "luma-d024", source: "luma", format: "conference", price: "free",
    title: "Developer Relations Day London", date: "Jun 20, 2026", location: "London, UK",
    topics: ["Community", "Open Source", "Networking"], attendeeProfile: "Developer advocates and community builders",
    url: "https://lu.ma/devrel-day-london",
  },
  {
    id: "luma-d025", source: "luma", format: "hackathon", price: "free",
    title: "Climate Tech Hackathon Barcelona", date: "Jun 24, 2026", location: "Barcelona, Spain",
    topics: ["Climate", "Startups", "AI"], attendeeProfile: "Developers passionate about sustainability",
    url: "https://lu.ma/climate-tech-hack-barcelona",
  },

  // ─── Meetup (25) ─────────────────────────────────────────────────────────────

  {
    id: "meetup-d001", source: "meetup", format: "meetup", price: "free",
    title: "Milano AI/ML Monthly Meetup", date: "Apr 2, 2026", location: "Milan, Italy",
    topics: ["AI", "Machine Learning", "Data Science"], attendeeProfile: "ML practitioners and AI enthusiasts",
    url: "https://www.meetup.com/milano-ai-ml/",
  },
  {
    id: "meetup-d002", source: "meetup", format: "meetup", price: "free",
    title: "Berlin React Developers", date: "Apr 6, 2026", location: "Berlin, Germany",
    topics: ["React", "JavaScript", "Frontend"], attendeeProfile: "Frontend developers",
    url: "https://www.meetup.com/berlin-react-developers/",
  },
  {
    id: "meetup-d003", source: "meetup", format: "meetup", price: "free",
    title: "London Python Users Group", date: "Apr 9, 2026", location: "London, UK",
    topics: ["Python", "Backend", "Data Science"], attendeeProfile: "Python developers",
    url: "https://www.meetup.com/londonpython/",
  },
  {
    id: "meetup-d004", source: "meetup", format: "meetup", price: "free",
    title: "Amsterdam DevOps Circle", date: "Apr 13, 2026", location: "Amsterdam, Netherlands",
    topics: ["DevOps", "Cloud", "Kubernetes"], attendeeProfile: "DevOps engineers and SREs",
    url: "https://www.meetup.com/amsterdam-devops/",
  },
  {
    id: "meetup-d005", source: "meetup", format: "meetup", price: "free",
    title: "Paris JavaScript Night", date: "Apr 16, 2026", location: "Paris, France",
    topics: ["JavaScript", "TypeScript", "Frontend"], attendeeProfile: "JavaScript developers",
    url: "https://www.meetup.com/paris-js/",
  },
  {
    id: "meetup-d006", source: "meetup", format: "meetup", price: "free",
    title: "Roma Web Developers", date: "Apr 20, 2026", location: "Rome, Italy",
    topics: ["Full Stack", "JavaScript", "Backend"], attendeeProfile: "Web developers",
    url: "https://www.meetup.com/roma-web-dev/",
  },
  {
    id: "meetup-d007", source: "meetup", format: "meetup", price: "free",
    title: "Barcelona UX Designers Meetup", date: "Apr 23, 2026", location: "Barcelona, Spain",
    topics: ["UX", "Design", "Product"], attendeeProfile: "UX designers and researchers",
    url: "https://www.meetup.com/barcelona-ux/",
  },
  {
    id: "meetup-d008", source: "meetup", format: "meetup", price: "free",
    title: "Madrid Cloud Architects", date: "Apr 27, 2026", location: "Madrid, Spain",
    topics: ["Cloud", "AWS", "DevOps"], attendeeProfile: "Cloud architects and engineers",
    url: "https://www.meetup.com/madrid-cloud/",
  },
  {
    id: "meetup-d009", source: "meetup", format: "meetup", price: "free",
    title: "Turin Startup Network", date: "Apr 30, 2026", location: "Turin, Italy",
    topics: ["Startups", "Networking", "Entrepreneurship"], attendeeProfile: "Founders and startup enthusiasts",
    url: "https://www.meetup.com/turin-startup-network/",
  },
  {
    id: "meetup-d010", source: "meetup", format: "meetup", price: "free",
    title: "Lisbon Tech Builders", date: "May 4, 2026", location: "Lisbon, Portugal",
    topics: ["Startups", "Product", "Community"], attendeeProfile: "Tech builders and makers",
    url: "https://www.meetup.com/lisbon-tech-builders/",
  },
  {
    id: "meetup-d011", source: "meetup", format: "meetup", price: "free",
    title: "Milano Blockchain Community", date: "May 7, 2026", location: "Milan, Italy",
    topics: ["Blockchain", "Web3", "DeFi"], attendeeProfile: "Blockchain developers and investors",
    url: "https://www.meetup.com/milano-blockchain/",
  },
  {
    id: "meetup-d012", source: "meetup", format: "meetup", price: "free",
    title: "Berlin Data Science Club", date: "May 11, 2026", location: "Berlin, Germany",
    topics: ["Data Science", "Analytics", "Machine Learning"], attendeeProfile: "Data scientists and analysts",
    url: "https://www.meetup.com/berlin-data-science/",
  },
  {
    id: "meetup-d013", source: "meetup", format: "meetup", price: "free",
    title: "London Kubernetes & Cloud Native", date: "May 14, 2026", location: "London, UK",
    topics: ["Kubernetes", "Cloud", "DevOps"], attendeeProfile: "Platform engineers",
    url: "https://www.meetup.com/london-kubernetes/",
  },
  {
    id: "meetup-d014", source: "meetup", format: "meetup", price: "free",
    title: "Amsterdam Product Managers Meetup", date: "May 18, 2026", location: "Amsterdam, Netherlands",
    topics: ["Product", "UX", "Startups"], attendeeProfile: "Product managers",
    url: "https://www.meetup.com/amsterdam-product/",
  },
  {
    id: "meetup-d015", source: "meetup", format: "meetup", price: "free",
    title: "Paris Cybersecurity Professionals", date: "May 21, 2026", location: "Paris, France",
    topics: ["Security", "Cybersecurity", "Privacy"], attendeeProfile: "Security engineers and analysts",
    url: "https://www.meetup.com/paris-cybersec/",
  },
  {
    id: "meetup-d016", source: "meetup", format: "meetup", price: "free",
    title: "Rome Fintech Community", date: "May 25, 2026", location: "Rome, Italy",
    topics: ["Fintech", "Payments", "Startups"], attendeeProfile: "Fintech builders and enthusiasts",
    url: "https://www.meetup.com/rome-fintech/",
  },
  {
    id: "meetup-d017", source: "meetup", format: "meetup", price: "free",
    title: "Barcelona Mobile Developers", date: "May 28, 2026", location: "Barcelona, Spain",
    topics: ["Mobile", "iOS", "Android"], attendeeProfile: "Mobile developers",
    url: "https://www.meetup.com/barcelona-mobile-dev/",
  },
  {
    id: "meetup-d018", source: "meetup", format: "meetup", price: "free",
    title: "Madrid Full Stack Developers Night", date: "Jun 1, 2026", location: "Madrid, Spain",
    topics: ["Full Stack", "JavaScript", "Backend"], attendeeProfile: "Full stack developers",
    url: "https://www.meetup.com/madrid-fullstack/",
  },
  {
    id: "meetup-d019", source: "meetup", format: "meetup", price: "free",
    title: "Turin Design Thinkers", date: "Jun 4, 2026", location: "Turin, Italy",
    topics: ["Design", "Product", "UX"], attendeeProfile: "Designers and product thinkers",
    url: "https://www.meetup.com/turin-design-thinking/",
  },
  {
    id: "meetup-d020", source: "meetup", format: "meetup", price: "free",
    title: "Lisbon Open Source Society", date: "Jun 8, 2026", location: "Lisbon, Portugal",
    topics: ["Open Source", "Community", "Linux"], attendeeProfile: "Open source contributors",
    url: "https://www.meetup.com/lisbon-oss/",
  },
  {
    id: "meetup-d021", source: "meetup", format: "meetup", price: "free",
    title: "Milano Women in Tech", date: "Jun 11, 2026", location: "Milan, Italy",
    topics: ["Community", "Networking", "Startups"], attendeeProfile: "Women in technology",
    url: "https://www.meetup.com/women-in-tech-milan/",
  },
  {
    id: "meetup-d022", source: "meetup", format: "meetup", price: "free",
    title: "Berlin Founders Circle", date: "Jun 15, 2026", location: "Berlin, Germany",
    topics: ["Startups", "Entrepreneurship", "VC"], attendeeProfile: "Tech founders and co-founders",
    url: "https://www.meetup.com/berlin-founders/",
  },
  {
    id: "meetup-d023", source: "meetup", format: "meetup", price: "free",
    title: "London Web3 Builders", date: "Jun 18, 2026", location: "London, UK",
    topics: ["Web3", "Blockchain", "Crypto"], attendeeProfile: "Web3 builders and investors",
    url: "https://www.meetup.com/london-web3/",
  },
  {
    id: "meetup-d024", source: "meetup", format: "meetup", price: "free",
    title: "Amsterdam AI Ethics Group", date: "Jun 22, 2026", location: "Amsterdam, Netherlands",
    topics: ["AI", "Machine Learning"], attendeeProfile: "AI researchers and ethicists",
    url: "https://www.meetup.com/amsterdam-ai-ethics/",
  },
  {
    id: "meetup-d025", source: "meetup", format: "meetup", price: "free",
    title: "Paris DevOps & SRE Night", date: "Jun 25, 2026", location: "Paris, France",
    topics: ["DevOps", "Cloud", "Kubernetes"], attendeeProfile: "DevOps engineers and SREs",
    url: "https://www.meetup.com/paris-devops/",
  },

  // ─── Ticketmaster (25) ───────────────────────────────────────────────────────

  {
    id: "tm-d001", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1295, currency: "EUR",
    title: "Web Summit 2026", date: "Apr 8, 2026", location: "Lisbon, Portugal",
    topics: ["Startups", "AI", "Networking"], attendeeProfile: "Tech leaders and startup founders",
    url: "https://websummit.com",
  },
  {
    id: "tm-d002", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 799, currency: "EUR",
    title: "TNW Conference 2026", date: "Apr 15, 2026", location: "Amsterdam, Netherlands",
    topics: ["Startups", "AI", "Product"], attendeeProfile: "Tech entrepreneurs and investors",
    url: "https://thenextweb.com/conference",
  },
  {
    id: "tm-d003", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 895, currency: "EUR",
    title: "VivaTech 2026", date: "Apr 21, 2026", location: "Paris, France",
    topics: ["Startups", "AI", "Innovation"], attendeeProfile: "Business leaders and innovators",
    url: "https://vivatechnology.com",
  },
  {
    id: "tm-d004", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1495, currency: "GBP",
    title: "Collision Conference London", date: "Apr 26, 2026", location: "London, UK",
    topics: ["Startups", "AI", "Networking"], attendeeProfile: "Startup founders and VCs",
    url: "https://collisionconf.com",
  },
  {
    id: "tm-d005", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 995, currency: "EUR",
    title: "DLD Conference Munich 2026", date: "May 3, 2026", location: "Munich, Germany",
    topics: ["AI", "Innovation", "Entrepreneurship"], attendeeProfile: "Business leaders and innovators",
    url: "https://dld-conference.com",
  },
  {
    id: "tm-d006", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1195, currency: "EUR",
    title: "Money 20/20 Europe 2026", date: "May 8, 2026", location: "Amsterdam, Netherlands",
    topics: ["Fintech", "Payments", "AI"], attendeeProfile: "Fintech executives and investors",
    url: "https://europe.money2020.com",
  },
  {
    id: "tm-d007", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1695, currency: "EUR",
    title: "Slush 2026", date: "May 12, 2026", location: "Helsinki, Finland",
    topics: ["Startups", "VC", "AI"], attendeeProfile: "Early-stage founders and investors",
    url: "https://slush.org",
  },
  {
    id: "tm-d008", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 595, currency: "EUR",
    title: "Tech Open Air Berlin 2026", date: "May 17, 2026", location: "Berlin, Germany",
    topics: ["Startups", "Community", "Networking"], attendeeProfile: "Tech professionals and creatives",
    url: "https://toa.berlin",
  },
  {
    id: "tm-d009", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 895, currency: "EUR",
    title: "AI World Summit Brussels", date: "May 22, 2026", location: "Brussels, Belgium",
    topics: ["AI", "Machine Learning", "Innovation"], attendeeProfile: "AI executives and researchers",
    url: "https://aiworldsummit.com",
  },
  {
    id: "tm-d010", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1999, currency: "EUR",
    title: "AWS re:Invent Europe", date: "May 27, 2026", location: "Amsterdam, Netherlands",
    topics: ["Cloud", "AWS", "DevOps"], attendeeProfile: "Cloud architects and developers",
    url: "https://reinvent.awsevents.com",
  },
  {
    id: "tm-d011", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 799, currency: "EUR",
    title: "Google I/O Extended Europe", date: "Jun 2, 2026", location: "Milan, Italy",
    topics: ["Cloud", "AI", "Mobile"], attendeeProfile: "Google developers and engineers",
    url: "https://io.google",
  },
  {
    id: "tm-d012", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1295, currency: "EUR",
    title: "Microsoft Build Europe", date: "Jun 5, 2026", location: "Paris, France",
    topics: ["Cloud", "AI", "DevOps"], attendeeProfile: "Microsoft developers and architects",
    url: "https://build.microsoft.com",
  },
  {
    id: "tm-d013", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1495, currency: "GBP",
    title: "Salesforce World Tour London", date: "Jun 9, 2026", location: "London, UK",
    topics: ["SaaS", "B2B", "Sales"], attendeeProfile: "Salesforce admins and developers",
    url: "https://salesforce.com/world-tour",
  },
  {
    id: "tm-d014", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 2995, currency: "EUR",
    title: "Gartner IT Symposium Barcelona", date: "Jun 14, 2026", location: "Barcelona, Spain",
    topics: ["Cloud", "AI", "Security"], attendeeProfile: "CIOs and IT executives",
    url: "https://gartner.com/symposium",
  },
  {
    id: "tm-d015", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 895, currency: "EUR",
    title: "KubeCon EU 2026", date: "Jun 16, 2026", location: "Copenhagen, Denmark",
    topics: ["Kubernetes", "Cloud", "DevOps"], attendeeProfile: "Platform engineers and cloud-native developers",
    url: "https://events.linuxfoundation.org/kubecon-cloudnativecon-europe",
  },
  {
    id: "tm-d016", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 695, currency: "EUR",
    title: "Black Hat Europe 2026", date: "Jun 19, 2026", location: "London, UK",
    topics: ["Security", "Cybersecurity"], attendeeProfile: "Security professionals and researchers",
    url: "https://blackhat.com/eu-26",
  },
  {
    id: "tm-d017", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1495, currency: "EUR",
    title: "RSA Conference Europe", date: "Jun 23, 2026", location: "Paris, France",
    topics: ["Security", "Cybersecurity", "Privacy"], attendeeProfile: "Security executives and practitioners",
    url: "https://rsaconference.com",
  },
  {
    id: "tm-d018", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 495, currency: "EUR",
    title: "NodeConf EU 2026", date: "Jun 26, 2026", location: "Kilkenny, Ireland",
    topics: ["JavaScript", "Backend", "Open Source"], attendeeProfile: "Node.js developers",
    url: "https://nodeconf.eu",
  },
  {
    id: "tm-d019", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 995, currency: "EUR",
    title: "Startup Grind Global Europe", date: "Jul 1, 2026", location: "London, UK",
    topics: ["Startups", "Entrepreneurship", "Networking"], attendeeProfile: "Startup founders and operators",
    url: "https://startupgrind.com/conference",
  },
  {
    id: "tm-d020", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1295, currency: "EUR",
    title: "HubSpot INBOUND Europe", date: "Jul 5, 2026", location: "Berlin, Germany",
    topics: ["Marketing", "Growth", "SaaS"], attendeeProfile: "Marketing and sales professionals",
    url: "https://inbound.com",
  },
  {
    id: "tm-d021", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 799, currency: "EUR",
    title: "Data + AI Summit Europe", date: "Jul 8, 2026", location: "Amsterdam, Netherlands",
    topics: ["AI", "Data Science", "Machine Learning"], attendeeProfile: "Data engineers and ML practitioners",
    url: "https://databricks.com/dataaisummit",
  },
  {
    id: "tm-d022", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 595, currency: "EUR",
    title: "PGConf Europe 2026", date: "Jul 11, 2026", location: "Barcelona, Spain",
    topics: ["Backend", "Open Source", "Data Science"], attendeeProfile: "Database engineers and developers",
    url: "https://pgconf.eu",
  },
  {
    id: "tm-d023", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 1095, currency: "EUR",
    title: "UX London 2026", date: "Jul 14, 2026", location: "London, UK",
    topics: ["UX", "Design", "Product"], attendeeProfile: "UX designers and researchers",
    url: "https://2026.uxlondon.com",
  },
  {
    id: "tm-d024", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 895, currency: "EUR",
    title: "CSSconf EU 2026", date: "Jul 17, 2026", location: "Berlin, Germany",
    topics: ["Frontend", "Design", "UI"], attendeeProfile: "Frontend developers and designers",
    url: "https://cssconf.eu",
  },
  {
    id: "tm-d025", source: "ticketmaster", format: "conference", price: "paid", priceAmount: 695, currency: "EUR",
    title: "JSConf EU 2026", date: "Jul 20, 2026", location: "Berlin, Germany",
    topics: ["JavaScript", "Frontend", "Open Source"], attendeeProfile: "JavaScript developers",
    url: "https://jsconf.eu",
  },

  // ─── Eventbrite (25) ─────────────────────────────────────────────────────────

  {
    id: "eb-d001", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 89, currency: "EUR",
    title: "AI Product Management Masterclass", date: "Apr 4, 2026", location: "Milan, Italy",
    topics: ["AI", "Product", "Startups"], attendeeProfile: "Product managers building AI features",
    url: "https://eventbrite.com/e/ai-product-management",
  },
  {
    id: "eb-d002", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 69, currency: "EUR",
    title: "Growth Hacking Workshop Berlin", date: "Apr 8, 2026", location: "Berlin, Germany",
    topics: ["Growth", "Marketing", "SaaS"], attendeeProfile: "Growth marketers and founders",
    url: "https://eventbrite.com/e/growth-hacking-berlin",
  },
  {
    id: "eb-d003", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 129, currency: "GBP",
    title: "Startup Legal Essentials London", date: "Apr 11, 2026", location: "London, UK",
    topics: ["Startups", "Fundraising"], attendeeProfile: "Early-stage startup founders",
    url: "https://eventbrite.com/e/startup-legal-london",
  },
  {
    id: "eb-d004", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 59, currency: "EUR",
    title: "Data Visualization with Python", date: "Apr 16, 2026", location: "Amsterdam, Netherlands",
    topics: ["Python", "Data Science", "Analytics"], attendeeProfile: "Data analysts and scientists",
    url: "https://eventbrite.com/e/dataviz-python-amsterdam",
  },
  {
    id: "eb-d005", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 79, currency: "EUR",
    title: "UX Research Methods Intensive", date: "Apr 19, 2026", location: "Paris, France",
    topics: ["UX", "Design", "Product"], attendeeProfile: "UX researchers and designers",
    url: "https://eventbrite.com/e/ux-research-paris",
  },
  {
    id: "eb-d006", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 99, currency: "EUR",
    title: "DevOps Fundamentals Bootcamp Rome", date: "Apr 23, 2026", location: "Rome, Italy",
    topics: ["DevOps", "Cloud", "Kubernetes"], attendeeProfile: "Developers transitioning to DevOps",
    url: "https://eventbrite.com/e/devops-bootcamp-rome",
  },
  {
    id: "eb-d007", source: "eventbrite", format: "conference", price: "paid", priceAmount: 149, currency: "EUR",
    title: "Blockchain for Business Barcelona", date: "Apr 27, 2026", location: "Barcelona, Spain",
    topics: ["Blockchain", "Web3", "Fintech"], attendeeProfile: "Business leaders exploring blockchain",
    url: "https://eventbrite.com/e/blockchain-business-barcelona",
  },
  {
    id: "eb-d008", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 49, currency: "EUR",
    title: "Sales Automation with AI", date: "Apr 30, 2026", location: "Madrid, Spain",
    topics: ["AI", "Sales", "B2B"], attendeeProfile: "Sales professionals and founders",
    url: "https://eventbrite.com/e/sales-automation-ai-madrid",
  },
  {
    id: "eb-d009", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 69, currency: "EUR",
    title: "React Native Cross-Platform Workshop", date: "May 5, 2026", location: "Turin, Italy",
    topics: ["React Native", "Mobile", "JavaScript"], attendeeProfile: "Mobile developers",
    url: "https://eventbrite.com/e/react-native-workshop-turin",
  },
  {
    id: "eb-d010", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 59, currency: "EUR",
    title: "SEO & Content Strategy Masterclass", date: "May 8, 2026", location: "Lisbon, Portugal",
    topics: ["Marketing", "Growth", "SaaS"], attendeeProfile: "Marketers and content creators",
    url: "https://eventbrite.com/e/seo-content-lisbon",
  },
  {
    id: "eb-d011", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 199, currency: "EUR",
    title: "Fundraising for Startups Bootcamp", date: "May 12, 2026", location: "Milan, Italy",
    topics: ["Startups", "Fundraising", "VC"], attendeeProfile: "Pre-seed and seed-stage founders",
    url: "https://eventbrite.com/e/fundraising-bootcamp-milan",
  },
  {
    id: "eb-d012", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 89, currency: "EUR",
    title: "MLOps Best Practices Workshop", date: "May 15, 2026", location: "Berlin, Germany",
    topics: ["Machine Learning", "DevOps", "Cloud"], attendeeProfile: "ML engineers and data scientists",
    url: "https://eventbrite.com/e/mlops-workshop-berlin",
  },
  {
    id: "eb-d013", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 79, currency: "GBP",
    title: "API Design & Architecture Workshop", date: "May 19, 2026", location: "London, UK",
    topics: ["Backend", "Full Stack", "Cloud"], attendeeProfile: "Backend developers",
    url: "https://eventbrite.com/e/api-design-london",
  },
  {
    id: "eb-d014", source: "eventbrite", format: "workshop", price: "free",
    title: "Design Thinking Sprint Amsterdam", date: "May 22, 2026", location: "Amsterdam, Netherlands",
    topics: ["Design", "Product", "UX"], attendeeProfile: "Product teams and designers",
    url: "https://eventbrite.com/e/design-thinking-amsterdam",
  },
  {
    id: "eb-d015", source: "eventbrite", format: "conference", price: "free",
    title: "Cybersecurity Awareness Day Paris", date: "May 26, 2026", location: "Paris, France",
    topics: ["Security", "Cybersecurity", "Privacy"], attendeeProfile: "IT professionals and developers",
    url: "https://eventbrite.com/e/cybersecurity-day-paris",
  },
  {
    id: "eb-d016", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 49, currency: "EUR",
    title: "E-commerce Growth Strategies", date: "May 29, 2026", location: "Rome, Italy",
    topics: ["Growth", "Marketing", "B2B"], attendeeProfile: "E-commerce founders and marketers",
    url: "https://eventbrite.com/e/ecommerce-growth-rome",
  },
  {
    id: "eb-d017", source: "eventbrite", format: "workshop", price: "free",
    title: "Web Accessibility Workshop Barcelona", date: "Jun 3, 2026", location: "Barcelona, Spain",
    topics: ["Frontend", "Design", "Community"], attendeeProfile: "Frontend developers and designers",
    url: "https://eventbrite.com/e/web-a11y-barcelona",
  },
  {
    id: "eb-d018", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 69, currency: "EUR",
    title: "Cloud Cost Optimization Workshop", date: "Jun 7, 2026", location: "Madrid, Spain",
    topics: ["Cloud", "AWS", "DevOps"], attendeeProfile: "Cloud engineers and CTOs",
    url: "https://eventbrite.com/e/cloud-cost-madrid",
  },
  {
    id: "eb-d019", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 59, currency: "EUR",
    title: "B2B Marketing Automation Masterclass", date: "Jun 10, 2026", location: "Turin, Italy",
    topics: ["B2B", "Marketing", "Growth"], attendeeProfile: "B2B marketers and founders",
    url: "https://eventbrite.com/e/b2b-marketing-turin",
  },
  {
    id: "eb-d020", source: "eventbrite", format: "workshop", price: "free",
    title: "Developer Portfolio Workshop", date: "Jun 14, 2026", location: "Lisbon, Portugal",
    topics: ["Community", "Networking", "Open Source"], attendeeProfile: "Junior and mid-level developers",
    url: "https://eventbrite.com/e/dev-portfolio-lisbon",
  },
  {
    id: "eb-d021", source: "eventbrite", format: "conference", price: "paid", priceAmount: 99, currency: "EUR",
    title: "AI Ethics in Practice", date: "Jun 17, 2026", location: "Milan, Italy",
    topics: ["AI", "Machine Learning"], attendeeProfile: "AI practitioners and policy makers",
    url: "https://eventbrite.com/e/ai-ethics-milan",
  },
  {
    id: "eb-d022", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 79, currency: "EUR",
    title: "Kubernetes for Developers Workshop", date: "Jun 21, 2026", location: "Berlin, Germany",
    topics: ["Kubernetes", "Cloud", "DevOps"], attendeeProfile: "Developers learning container orchestration",
    url: "https://eventbrite.com/e/kubernetes-devs-berlin",
  },
  {
    id: "eb-d023", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 129, currency: "GBP",
    title: "Product Analytics Masterclass", date: "Jun 24, 2026", location: "London, UK",
    topics: ["Product", "Analytics", "Data Science"], attendeeProfile: "Product managers and analysts",
    url: "https://eventbrite.com/e/product-analytics-london",
  },
  {
    id: "eb-d024", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 59, currency: "EUR",
    title: "GraphQL Workshop Amsterdam", date: "Jun 28, 2026", location: "Amsterdam, Netherlands",
    topics: ["Backend", "Full Stack", "JavaScript"], attendeeProfile: "Full stack developers",
    url: "https://eventbrite.com/e/graphql-workshop-amsterdam",
  },
  {
    id: "eb-d025", source: "eventbrite", format: "workshop", price: "paid", priceAmount: 149, currency: "EUR",
    title: "Leadership for Tech Leads", date: "Jul 2, 2026", location: "Paris, France",
    topics: ["Startups", "Networking", "Entrepreneurship"], attendeeProfile: "Senior engineers moving into leadership",
    url: "https://eventbrite.com/e/leadership-tech-leads-paris",
  },
];

export default createStubProvider("mock", DEMO_EVENTS);
